@startuml カレーライス
title カレーライス

start

fork
    :お米を洗う;
    :水を入れる;    
    :炊飯器に入れる;
    :炊飯スイッチを押す;
    :ご飯が炊ける;

    fork again

    :玉ねぎを切る;
    :人参を切る;
    :ジャガイモを切る;
    :お肉を切る;
    :玉ねぎを炒める;
    :お肉を炒める;
    :ジャガイモと人参も入れて炒める;
    :玉ねぎも入れて炒める;
    :水入れて煮る;
    :カレールーを入れる;
    :ちょっと煮る;
end fork

:お皿に盛り付ける;

:食べる;

stop

@enduml