@startuml a
    left to right direction
    高度情報工学科 "1" -- "*" 学生
    会社 -----> 社員 : 雇う >
    会員リスト o-- 会員
    note right of 会員リスト
        部分クラスがなくて成り立ちます。
    end note

    パソコン "1" *-- ハードディスク
    note right of パソコン
        ハードディスクがないと成り立ちません。
    end note

    注文 <.. 注文管理
    note right of 注文管理
        注文管理が注文のメソッドもしくは属性を呼び出している
    end note
@endyaml
