@startuml
' 継承
    class 社員{
        - 社員ID
        - 社員名
        ---
        + 社員ID設定（社員ID:int）:void
        + 社員ID取得（）:int
        + 社員名設定（社員名:String）:void
        + 社員名取得（）:String
    }
    class 技術社員{
        - プロジェクト名:String
        ---
        + プロジェクト名設定（プロジェクト名:String）:void
        + プロジェクト名取得（）:String
    }
    class 営業社員{
        - 担当地域名:String
        ---
        + 担当地域名設定（プロジェクト名:String）:void
        + 担当地域名取得（）:String
    }

    社員<|--down- 技術社員
    社員<|--down- 営業社員
' -----------------------

' 抽象
    class Animal {
        ---
        + Walk():void
        + {abstract} eat():int
        + {abstract} cry():void
    }
    class Dog {
        ---
        + eat():int
        + cry():void
    }
    class Cat {
        ---
        + eat():int
        + cry():void
    }

    Animal <|-down- Dog
    Animal <|-down- Cat
' ---------------------

' インターフェース
    ' class Word {
    '     ---
    '     + enter():void
    ' }
    ' class Excel {
    '     ---
    '     + enter():void
    ' }
    ' interface keyboard {
    '     ' <<interface>>
    '     ---
    '     + enter():void
    ' }

    ' keyboard <|.. Word
    ' keyboard <|.. Excel

    ' class User {

    ' }
    ' keyboard <-up- User:<< use >>
' ---------------------
' インターフェース ロリポップ
    class Word {
        ---
        + enter():void
    }
    class Excel {
        ---
        + enter():void
    }
    circle "keyboard" as I1
    Word --( I1
    Excel --( I1
    class User {

    }
    I1 <-- User:<< use >>
' ---------------------
@enduml