@startuml class
    ' 可視性をアイコンにしないオプション
    skinparam classAttributeIconSize 0
    
    ' class A <<stereotype>> {}

    ' class B {
    '     - 属性1 : int
    '     - 属性2 : String
    ' }

    ' class C {
    '     ---
    '     + 操作1() : void
    '     + 操作2() : String
    ' }

    ' class D {
    '     - 属性1 : int
    '     - 属性2 : String
    '     ---
    '     +操作1() : void
    '     +操作2() : String
    ' }

    class Employee {
        - id : int = 0
        - name : String
        # depertment : String
        / 勤続年数 : int
        ---
        + setId(id:int) : void
        + getId() : int
        + setName(name:String) : void
        + getName() : String
        + setDept(dept:Stirng) : void
        + getDept() : String
    }
@enduml