@startuml 自動販売機
' left to right direction

[*] --> 料金投入待ち
料金投入待ち -right-> ボタン選択待ち : 硬貨投入/ボタンランプ点灯
' ボタン選択待ち -right-> 料金投入待ち : キャンセル
ボタン選択待ち -right-> ドリンク排出中 : ボタンが選択
ドリンク排出中 --> [*]

' 料金投入待ち
' ボタン選択待ち
' ドリンク排出中

@enduml