@startuml 販売管理システム
    left to right direction
    actor 出荷担当者 as A1

    rectangle 販売管理システム {
        usecase 注文商品を確認する as U1
        usecase 出荷状況の登録をする as U2
    }

    A1 --> U1
    A1 --> U2

@enduml