@startuml
    hide footbox
    actor ":ユーザ" as user
    participant ":ブラウザ" as blouser
    participant ":Webサーバー" as web
    participant ":画像サーバー" as images

    activate user
        user -> blouser : 閲覧画面情報(リンク)
        activate blouser
            blouser -> web: 閲覧画像情報(画像ファイル名)
            activate web
                web -> images : 画像検索(画像ファイル名)
                activate images
                    images -> images : 画像検索(画像ファイル名)
                    activate images
                    deactivate images
                    web <-- images : 画像変換(画像ファイル)
                deactivate images
                blouser <-- web : 画像再生(変換済み画像ファイル)
            deactivate web
        deactivate blouser
    deactivate user
@enduml