@startuml
    hide footbox
    actor ":ユーザ" as user
    participant ":ブラウザ" as blouser
    participant ":Webサーバー" as web
    participant ":画像サーバー" as images

    activate user
        user -> blouser : 画像のリンクボタンを押す
        activate blouser
            blouser -> web: 画像ファイル名を渡す
            activate web
                web -> images : 画像ファイル名を探す命令を渡す
                activate images
                    images -> images : 画像ファイルを探す
                    activate images
                    deactivate images
                    web <-- images : 画像ファイル
                deactivate images
                blouser <-- web : HTMLと画像ファイル
            deactivate web
            user <<-- blouser : 画像の閲覧
        deactivate blouser
    deactivate user
@enduml