@startuml 資格取得
    left to right direction
    object "<u>社員１:社員</u>" as O1 {
        名前 = 高橋洋平
    }
    object "<u>社員２:社員</u>" as O2 {
        名前 = 樋口正之
    }
    object "<u>資格１:資格</u>" as O3 {
        名称 = 情報処理技術者試験の情報処理安全確保支援士
    }
    object "<u>資格２:資格</u>" as O4 {
        名称 = LinuC試験Level1
    }

    O1 -- O3
    O1 -- O4
    O2 -- O3

@enduml