' 車にはタイヤが４本装着されている。車クラスとタイヤクラスの関係を①オブジェクト図と②クラス図で表現しなさい。
@startuml 車
    left to right direction
    object "<u>車１:車</u>" as O1 {
        車体識別番号
        車種
    }

    object "<u>タイヤ１:タイヤリスト</u>" as O2 {
        タイヤ識別番号
        車体識別番号
        種類
    }
    object "<u>タイヤ２:タイヤリスト</u>" as O3 {
        タイヤ識別番号
        車体識別番号
        種類
    }
    object "<u>タイヤ３:タイヤリスト</u>" as O4 {
        タイヤ識別番号
        車体識別番号
        種類
    }
    object "<u>タイヤ４:タイヤリスト</u>" as O5 {
        タイヤ識別番号
        車体識別番号
        種類
    }

    O1 -- O2
    O1 -- O3
    O1 -- O4
    O1 -- O5
    
@enduml