@startuml 診察予約システム
    ' left to right direction
    [*] -right-> メニュー

    メニュー --> 予約と確認 : 予約と確認ボタンを押す
    メニュー <-- 予約と確認 : 取消ボタンを押す
    予約と確認 -right-> あなたの順番 : 登録ボタンを押す
    予約と確認 -right-> あなたの順番 : 確認ボタンを押す
    メニュー <-- あなたの順番 : メニューへボタンを押す
    メニュー <-- 今の順番 : メニューへボタンを押す
    メニュー --> 今の順番 : 今の順番ボタンを押す
    メニュー -right-> [*]
@enduml