' 下記のクラス図は注文のモデルです。次のシナリオに基づいて、オブジェクト図を作成しな
' さい。
' 【シナリオ】
' 　11月21日、重要顧客の高橋洋平さんが売り場に来られて、テレビ（型式V12345）を２台
' と冷蔵庫（型式R8765）１
' 台注文していきました。12月23日高田利恵さんも同じ冷蔵庫を1台注文していきました。
' 12月30日に大坪直之さん
' が来店し、売り場のプロジェクタ（型式P1122）を熱心に見ていましたが、
' 残念ながら注文せずにお帰りになりました。
@startuml 注文
    left to right direction
    object "<u>顧客１:顧客</u>" as O1 {
        氏名 = 高橋洋平
        住所
    }
    object "<u>顧客２:顧客</u>" as O2 {
        氏名 = 髙田利恵
        住所
    }
    ' object "<u>顧客３:顧客</u>" as  {
    '     氏名 = 大坪直之
    '     住所
    ' }
    object "<u>商品１:商品</u>" as O3 {
        商品名 = テレビ
        型式 = V12345
    }
    object "<u>商品２:商品</u>" as O4 {
        商品名 = 冷蔵庫
        型式 = R8765
    }
    ' object "<u>商品３:商品</u>" as  {
    '     商品名 = プロジェクタ（型式P1122）
    ' }

    O1 -- O3
    O1 -- O4
    O2 -- O4

@enduml