@startuml 注文
    left to right direction
    object "<u>顧客１:顧客</u>" as O1 {
        氏名 = 高橋洋平
        住所
    }
    object "<u>顧客２:顧客</u>" as O2 {
        氏名 = 髙田利恵
        住所
    }
    object "<u>顧客３:顧客</u>" as O3 {
        氏名 = 大坪直之
        住所
    }

    object "<u>商品１:商品</u>" as O4 {
        商品名 = テレビ
        型式 = V12345
    }
    object "<u>商品２:商品</u>" as O5 {
        商品名 = 冷蔵庫
        型式 = R8765
    }
    object "<u>商品３:商品</u>" as O6 {
        商品名 = プロジェクタ
        型式 = P1122
    }

    object "<u>注文１:注文</u>" as O7 {
        商品 = テレビ
        個数 = 2
        注文日 = 11月21日
    }
    object "<u>注文２:注文</u>" as O8 {
        商品 = 冷蔵庫
        個数 = 1
        注文日 = 11月21日
    }
    object "<u>注文３:注文</u>" as O9 {
        商品 = 冷蔵庫
        個数 = 1
        注文日 = 2月23日
    }
    object "<u>重要顧客１:重要顧客</u>" as 10 {

    }

    O1 -- O7
    O1 -- O8
    O2 -- O9

    O7 -- O4
    O8 -- O5
    O9 -- O5

    10 -- O1
    O3 -- O6



@enduml