@startuml ホテル宿泊予約
    left to right direction
    object "<u>A:利用者</u>" as O1 {
        名前 = A
    } 
    object "<u>B:利用者</u>" as O2 {
        名前 = B
    }
    object "<u>301号室:部屋</u>" as O3 {
        部屋番号 = 301
        宿泊費 = 11,000
        部屋タイプ = シングル
    }
    object "<u>301号室:部屋</u>" as O4 {
        部屋番号 = 302
        宿泊費 = 11,000
        部屋タイプ = シングル
    }
    object "<u>302号室:部屋</u>" as O5 {
        部屋番号 = 303
        宿泊費 = 11,000
        部屋タイプ = シングル
    }
    object "<u>キャンペーン:キャンペーン</u>" as O6 {
        キャンペーン期間 開始 = 4月29日
        キャンペーン期間 終了 = 5月6日
        キャンペーン価格 = 9,000
    }

    object "<u>予約１:予約</u>" as O7 {
        チェックイン日 = 5月3日
        滞在期間 = 2
        部屋番号 = 301
    }
    object "<u>予約２:予約</u>" as O8 {
        チェックイン日 = 5月3日
        滞在期間 = 2
        部屋番号 = 301
    }

    O1 -- O7
    O2 -- O8
    O3 -- O6
    O5 -- O6
    O7 -- O3
    O8 -- O5
@enduml