' 「自動販売機」「ボタン」「料金装置」「ベンダー装置」をクラスとして、クラス図を作成してくだ
' さい。

@startuml 自動販売機
    left to right direction
    class "自動販売機" as C1 {
    }
    class "ボタン" as C2 {
    }
    class "料金装置" as C3 {
    }
    class "ベンダー装置" as C4 {
    }

    C1 "1"--"10" C2
    C1 "1"--"1" C3
    C1 "1"--"1" C4

@enduml