@startuml プリンタ
    ' left to right direction

    [*] -right-> 待機中 : 電源ON
    待機中 -right-> [*] : 電源OFF

    待機中 --> 印刷中 : 印刷
    待機中 <-- 印刷中 : 印刷完了
    印刷中 --> 用紙無し : 用紙切れ
    印刷中 <-- 用紙無し : 用紙補充

@enduml