@startuml 製造
title 製造
|【販売代理店】|
start
:発注;
|【営業部門】|
:受注;
:在庫調査;
if () is  ([在庫あり]) then
    :;
else ([在庫なし])
    |【製造部門】|
    :製造;
endif

|【営業部門】|
:発送;

|【販売代理店】|
:検収/支払い;

|【営業部門】|
:入金確認;

stop


@enduml