' 下記の図は、社員の資格取得状況を記録するためのシステムのクラス図の一部です。
' 次のシナリオに基づ
' いて、オブジェクト図を記述しなさい。
' 【シナリオ】
' 　高橋洋平さんは、情報処理技術者試験の情報処理安全確保支援士の試験に合格し、2020年10月21日
' にそのことを申請しました。樋口正之さんもその試験に合格しています。さらに、高橋洋平さんは、
' LinuC試
' 験Level１も合格し、2021年3月28日に会社に申し出ました。
@startuml 資格取得
    left to right direction
    object "<u>社員１:社員</u>" as O1 {
        名前 = 高橋洋平
    }
    object "<u>社員２:社員</u>" as O2 {
        名前 = 樋口正之
    }
    object "<u>資格１:資格</u>" as O3 {
        名称 = 情報処理技術者試験の情報処理安全確保支援士
    }
    object "<u>資格２:資格</u>" as O4 {
        名称 = LinuC試験Level1
    }

    O1 -- O3
    O1 -- O4
    O2 -- O3

@enduml