' ● ホテルには部屋が複数個（いくつかは不明）あります。
' ● ホテルには利用者が会員として登録されています。
' ● 利用者は部屋を予約します。
' 集約、コンポジション、関連を適切に表現しましょう。

@startuml ホテル
    left to right direction
    class "利用者" as C1 {
        - 名前
        - 住所
        - 電話番号
    }
    class "ホテル" as C2 {
        - 部屋
    }
    class "部屋" as C3 {
        - タイプ
        - 価格
        - キャンペーン価格
    }
    class "予約" as C4 {
        - チェックイン日
        - 滞在期間
        - 値段
    }

    C1 "1" --> "0..1" C4
    C2 "1" o-- "1" C3
    C3 "1" -- "*" C4
    

    
@enduml