@startuml 診察予約システム
    ' left to right direction
    
    ' [*] -right-> 接続
    
    ' state c <<choice>>

    ' 接続 -right-> メニュー画面表示中
    ' メニュー画面表示中 --> c
    ' c --> 操作待機中 : 予約と確認ボタンを押す
    ' c --> 今の順番表示中 : 今の順番ボタンを押す

    ' state c2 <<choice>>

    ' 操作待機中 --> c2
    ' c2 --> 登録中 : 登録ボタンを押す[名前・電話番号を入力]
    ' c2 --> 確認中 : 確認ボタンを押す[名前または電話番号を入力]
    ' c2 --> 取り消し中 : 取消ボタンを押す[名前または電話番号を入力]

    ' 登録中 --> 順番表示中
    ' 確認中 --> 順番表示中
    ' 取り消し中 --> メニュー画面表示中 : メニューへボタンを押す
    ' 順番表示中 --> メニュー画面表示中 : メニューへボタンを押す
    ' 今の順番表示中 --> メニュー画面表示中 : メニューへボタンを押す
    ' メニュー画面表示中 -right-> 切断 : 終わりボタンを押す
    ' 切断 -right-> [*]

    ' ----------
' ※ステートマシン図記述の際の注意点　
' スマートフォンの４つの画面を状態オブジェクトとします　
' ４つの画面：メニュー、予約と確認、あなたの順番、今の順
    [*] --> メニュー
    メニュー --> 今の順番 : 今の順番ボタンを押す
    メニュー --> 予約と確認 : 予約と確認ボタンを押す

    state c <<choice>>

    予約と確認 --> c
    c --> あなたの順番 : 予約ボタンが押された[名前と電話番号を入力]/予約登録する
    c --> あなたの順番 : 確認ボタンが押された[名前もしくは電話番号を入力]
    c --> メニュー : 取消ボタンを押す[名前または電話番号を入力]

    あなたの順番 --> メニュー : メニューボタンが押された
    今の順番 --> メニュー : メニューボタンが押された
    メニュー -up-> [*]



@enduml