' 車にはタイヤが４本装着されている。車クラスとタイヤクラスの関係を①オブジェクト図と②クラス図で表現しなさい。
@startuml 車
    left to right direction
    class "車" as C1 {
        車体識別番号
        車種
    }
    class "タイヤリスト" as C2 {
        タイヤ識別番号
        車体識別番号
        種類
    }

    C1 "1" *-- "4" C2 
@enduml