@startuml 注文
    left to right direction
    object "<u>顧客１:顧客</u>" as O1 {
        氏名 = 高橋洋平
        住所
    }
    object "<u>顧客２:顧客</u>" as O2 {
        氏名 = 髙田利恵
        住所
    }

    object "<u>商品１:商品</u>" as O3 {
        商品名 = テレビ
        型式 = V12345
    }
    object "<u>商品２:商品</u>" as O4 {
        商品名 = 冷蔵庫
        型式 = R8765
    }

    O1 -- O3
    O1 -- O4
    O2 -- O4

@enduml