@startuml 演習2-4
    left to right direction
    actor 利用者
    rectangle ホテル宿泊予約 {
        usecase キャンペーン
        usecase (<u>予約</u>\n拡張点\nキャンペーン期間) as U
        usecase ログイン
    }

    利用者 -down-> U 
    キャンペーン ..> U : <<extend>>
    U ..> ログイン : <<include>>

@enduml