' 次の文章の条件を満たすオブジェクト図を完成させなさい。なお、属性に具体的な値が
' あるクラスは属性値を表記
' し、ないクラスは省略形で表記しなさい。
' 　AさんとBさんがホテルUMLに宿泊をしました。客室のタイプはシングル、
' 宿泊費は一泊11,000円、キャンペーン価
' 格9,000円の部屋です。チャックイン日は、5月3日で2泊の予定です。4月29日から
' 5月6日まではキャンペーン期間
' です。システムはAさんの宿泊予定の客室を301号室、Bさんの宿泊予定の客室を304号室
' としました。
' 　　１．予約のオブジェクトは、省略する
' 　　２。へやのオブジェクト名は、301号室、302号室とする

@startuml ホテル宿泊予約
    left to right direction
    object "<u>A:利用者</u>" as O1 {
        名前 = A
    } 
    object "<u>B:利用者</u>" as O2 {
        名前 = B
    }
    object "<u>301号室:部屋</u>" as O3 {
        部屋番号 = 301
        宿泊費 = 11,000
        部屋タイプ = シングル
    }
    object "<u>302号室:部屋</u>" as O4 {
        部屋番号 = 304
        宿泊費 = 11,000
        部屋タイプ = シングル
    }
    object "<u>キャンペーン:キャンペーン</u>" as O5 {
        キャンペーン期間 開始 = 4月29日
        キャンペーン期間 終了 = 5月6日
        キャンペーン価格 = 9,000
    }

    O1 -- O3
    O2 -- O4
    O3 -- O5
    O4 -- O5

@enduml