@startuml 診察予約システム
    left to right direction

    actor 利用者 as user
    actor 看護師 as nurse

    rectangle 診察予約システム {
        usecase メニュー as U1
        usecase 予約と確認 as U2
        usecase あなたの順番 as U3
        usecase 今の順番 as U4
    }

    user --> U1
    user --> U2
    user --> U3
    user --> U4
    U4 <-- nurse

@enduml